# s3_app/template.yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM App

Parameters:
  EnvironmentType:
    Type: String
    Description: API Gateway deployment stage
    Default: dev
    AllowedValues:
      - dev
      - prod

  Architecture:
    Type: String
    Description: Lambda CPU architecture
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64

  ApiDefinitionLocation:
    Type: String
    Description: S3 URL for OpenAPI definition

Globals:
  Function:
    Handler: app.handler
    Runtime: python3.9
    Timeout: 10
    Architectures:
      - Ref: Architecture

Resources:
  MyBucket:
    Type: AWS::S3::Bucket

  # REST API
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Hello World REST API
      StageName:
        Ref: EnvironmentType
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
      OpenApiVersion: "3.0.1"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Ref: ApiDefinitionLocation

  # Lambda functions (REST API)
  ListObjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/s3_app/list_objects
      Description: List objects function
      Environment:
        Variables:
          MY_BUCKET:
            Ref: MyBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /objects
            RestApiId:
              Ref: HelloWorldApi

  CreateObjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/s3_app/create_object
      Description: Create object function
      Environment:
        Variables:
          MY_BUCKET:
            Ref: MyBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: PUT
            Path: /objects/{key}
            RestApiId:
              Ref: HelloWorldApi

  GetObjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/s3_app/get_object
      Description: Get object function
      Environment:
        Variables:
          MY_BUCKET:
            Ref: MyBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /objects/{key}
            RestApiId:
              Ref: HelloWorldApi

  DeleteObjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/s3_app/delete_object
      Description: Delete object function
      Environment:
        Variables:
          MY_BUCKET:
            Ref: MyBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: DELETE
            Path: /objects/{key}
            RestApiId:
              Ref: HelloWorldApi

  # Permissions
  ListObjectsFunctionMyBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ListObjectsFunction
      Destination:
        Id: MyBucket
      Permissions:
        - Read

  CreateObjectFunctionMyBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: CreateObjectFunction
      Destination:
        Id: MyBucket
      Permissions:
        - Write

  GetObjectFunctionMyBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: GetObjectFunction
      Destination:
        Id: MyBucket
      Permissions:
        - Read

  DeleteObjectFunctionMyBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: DeleteObjectFunction
      Destination:
        Id: MyBucket
      Permissions:
        - Write

Outputs:
  HelloWorldApiId:
    Value:
      Ref: HelloWorldApi
  HelloWorldApiUrl:
    Value:
      Fn::Sub: https://${HelloWorldApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${HelloWorldApi.Stage}
  MyBucketName:
    Value:
      Ref: MyBucket
