version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - sam build
      - sam package --s3-bucket ${S3_BUCKET} --s3-prefix ${S3_PREFIX} --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
