AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-python infra stack

Parameters:
  ProjectName:
    Type: String
    Description: Project name
    Default: aws-sam-python

Resources: {}

Outputs: {}
