version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws_lambda_typing
      - pip install boto3
      - pip install jsonschema
      - pip install pytest
      - pip install pytest-cov
      - pip install pytest-mock
  build:
    commands:
      - ./buildspecs/${APP_NAME}/test-unit.sh hello_world

artifacts:
  files:
    - "**/*"
  base-directory: reports/${APP_NAME}

reports:
  coverage:
    files:
      - coverage.xml
    base-directory: reports/${APP_NAME}
    file-format: COBERTURAXML

  test:
    files:
      - "*.xml"
    base-directory: reports/${APP_NAME}/junit
    file-format: JUNITXML
