version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws_lambda_typing
      - pip install boto3
      - pip install jsonschema
      - pip install pytest
      - pip install pytest-cov
  build:
    commands:
      - ./cicd/hello_world_app/test-unit.sh

artifacts:
  files:
    - "**/*"
  base-directory: tests/report/htmlcov/hello_world_app

reports:
  coverage:
    files:
      - tests/report/clover/hello_world_app/*.xml
    discard-paths: yes
    file-format: COBERTURAXML

  test:
    files:
      - tests/report/junit/hello_world_app/*.xml
    discard-paths: yes
    file-format: JUNITXML
